services:
  taskflow-mongo:
    image: mongo:7
    container_name: taskflow-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=taskflow-app
    ports:
      - "27017:27017"
    networks:
      - taskflow-network

networks:
  taskflow-network:
    driver: bridge